/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tes;

import Connect.DBConnect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Irawan Papang Subakt
 */
public class NewJFrame extends javax.swing.JFrame {
    
    Connection c = DBConnect.getKoneksi();
    ResultSet r;
    Statement s;
    
    public NewJFrame() {
        initComponents();
        update_table_kelompok();
//        MyObjectManager manager = new radio1.MyObjectManager();
//        for (int i = 0; i < 200; i++) {
//            radio1.MyObject object = new radio1.MyObject("Row " + (i + 1));
//            manager.addObject(object);
//        }
//        table = new JTable(new radio1.MyTableModel(manager));
//        table.setRowHeight(20);
//        TableColumn column = jTable1.getColumnModel().getColumn(1);
//        jTable1.getColumnModel().getColumn(0).setCellEditor(new radio1.RadioButtonCellEditorRenderer());
//        jTable1.getColumnModel().getColumn(0).setCellRenderer(new radio1.RadioButtonCellEditorRenderer());
        
//        column.setCellEditor(new radio1.RadioButtonCellEditorRenderer());
    }

    public void update_table_kelompok() {
        DefaultTableModel model = new DefaultTableModel() {

            public Class<?> getColumnClass(int colom) {

                switch (colom) {
                    case 0:
                        return String.class;
                    case 1:
                        return String.class;
                    case 2:
                        String a = "";
                        return Boolean.class;

                    default:
                        return String.class;
                }
            }
        };

        jTable1.setModel(model);
        model.addColumn("NO");
        model.addColumn("NAMA");
        model.addColumn("CHECK");

        try {
            String sql = "SELECT\n"
                    + "alternatif.seq,\n"
                    + "alternatif.alternatif_name,\n"
                    + "alternatif.kategori_seq\n"
                    + "FROM\n"
                    + "alternatif";

            s = c.createStatement();
            r = s.executeQuery(sql);

            int n = 0;
            while (r.next()) {
                model.addRow(new Object[2]);
                model.setValueAt((n + 1), n, 0);
                model.setValueAt(r.getString("alternatif.alternatif_name"), n, 1);
                model.setValueAt(false+"a", n, 2);
                n = n + 1;
            }
            jTable1.setModel(model);
        } catch (Exception e) {
        } finally {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
